name: CI
on: [push]

jobs:
  build-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install cloud functions dependencies
        run: |
          cd functions
          yarn
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
